DELETE FROM rcv_map_ctieu_bthue
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(1,'06','0101','012','03')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(2,'06','010101','012','03')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(4,'06','010201','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(5,'06','010202','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(6,'06','010203','012','03')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(7,'06','010204','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(8,'06','010205','012','03')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(9,'06','010206','012','03')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(11,'06','020101','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(12,'06','020102','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(14,'06','020201','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(16,'06','020301','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(17,'06','020302','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(18,'06','0206','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(19,'06','0301','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(20,'06','0302','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(21,'06','0303','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(22,'06','0304','012','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(23,'06','0401','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(24,'06','0402','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(25,'06','0403','012','04')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(26,'06','0501','012','01')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(27,'06','0601','012','01')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(29,'06','070101','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(30,'06','070102','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(31,'06','070103','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(32,'06','070104','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(33,'06','0702','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(34,'06','0703','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(35,'06','0704','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(36,'06','0705','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(37,'06','0706','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(38,'06','0707','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(40,'06','070801','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(41,'06','070802','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(42,'06','070803','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(44,'06','070901','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(45,'06','070902','012','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(46,'06','0801','012','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(47,'06','0802','012','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(48,'06','0901','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(49,'06','0902','012','02')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(51,'06','090301','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(52,'06','090302','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(53,'06','090303','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(54,'06','0904','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(55,'06','1001','012','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(56,'06','1101','012','99')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(60,'05','10101','015','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(61,'05','10102','015','05')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(62,'05','10201','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(63,'05','10202','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(64,'05','10203','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(65,'05','10301','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(66,'05','10302','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(67,'05','10303','015','06')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(68,'05','10401','015','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(69,'05','10402','015','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(70,'05','10403','015','07')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(71,'05','10500','015','08')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(72,'05','10600','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(73,'05','10700','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(74,'05','10800','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(75,'05','20100','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(76,'05','20200','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(77,'05','20300','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(78,'05','20400','015','09')
/
INSERT INTO rcv_map_ctieu_bthue
VALUES
(79,'05','20500','015','09')
/
