DELETE FROM rcv_map_ctieu
WHERE (loai_dlieu NOT LIKE '01%')
AND (loai_dlieu NOT LIKE '02%')
AND (loai_dlieu NOT LIKE '03%')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','3','C',411,'154')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','7','C',414,'144')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','10','C',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','21','C',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','32','C',417,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','54','C',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','36','C',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','42','C',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','48','C',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','4','C',411,'154')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','11','C',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','20','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','31','N',417,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','53','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','35','N',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','41','N',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','47','N',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','22','C',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','37','C',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','43','C',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','49','C',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','12','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','23','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','38','N',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','44','N',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','50','N',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','13','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','24','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','33','N',417,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','55','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','39','N',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','45','N',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','51','N',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','14','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','25','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','56','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','15','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','26','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','57','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','16','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','27','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','58','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','17','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','28','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','59','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','18','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','29','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','60','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','1','N',411,'154')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','5','N',414,'144')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','8','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','19','N',416,'146')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','30','N',417,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','52','N',426,'148')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','34','N',429,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','40','N',430,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','46','N',431,'147')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','2','N',411,'154')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','6','N',414,'144')
/
INSERT INTO rcv_map_ctieu
VALUES
('0501','9','N',415,'145')
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','1','N',396,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','2','N',397,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','3','N',398,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','4','N',399,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','5','N',400,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','6','N',401,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0401','7','N',402,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','1','N',403,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','2','N',404,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','3','N',405,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','4','N',406,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','5','N',407,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0701','6','N',408,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','1','C',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','2','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','3','C',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','4','C',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','5','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','6','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','7','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','8','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','9','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','1','C',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','2','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','3','C',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','4','C',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','5','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','6','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','7','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','8','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','9','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','10','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','10','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','11','N',410,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','11','N',409,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','12','N',413,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','13','N',413,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0601','14','N',413,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','12','N',412,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','13','N',412,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0801','14','N',412,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','2','C',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','9','C',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','16','C',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','23','C',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','30','C',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','37','C',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','44','C',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','51','C',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','58','C',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','3','D',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','10','D',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','17','D',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','24','D',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','31','D',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','38','D',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','45','D',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','52','D',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','59','D',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','4','N',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','11','N',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','18','N',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','25','N',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','32','N',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','39','N',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','46','N',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','53','N',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','60','N',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','5','N',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','12','N',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','19','N',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','26','N',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','33','N',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','40','N',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','47','N',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','54','N',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','61','N',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','6','N',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','13','N',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','20','N',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','27','N',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','34','N',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','41','N',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','48','N',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','55','N',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','62','N',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','7','C',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','14','C',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','21','C',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','28','C',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','35','C',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','42','C',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','49','C',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','56','C',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','63','C',427,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','1','N',418,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','8','N',419,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','15','N',420,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','22','N',421,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','29','N',422,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','36','N',423,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','43','N',424,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','50','N',425,NULL)
/
INSERT INTO rcv_map_ctieu
VALUES
('0502','57','N',427,NULL)
/
