ALTER TABLE QLT_NTK.RCV_TKHAI_HDR ADD (LOAI_TK_DK VARCHAR2(10));
alter table QLT_NTK.RCV_TKHAI_HDR add  (NGAY_XUAT_BAN_DK DATE);
alter table QLT_NTK.RCV_TKHAI_HDR add  (LAN_XUAN_BAN_DK VARCHAR2(5));	
alter table QLT_NTK.RCV_TKHAI_HDR add  (TKHAI_QCT VARCHAR2(1));	