--01_TAIN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '1', 'C', 8050, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '2', 'C', 8051, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '3', 'C', 8052, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '4', 'D', 8053, '10');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '5', 'C', 8054, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '6', 'C', 8055, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '7', 'C', 8056, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '8', 'C', 8057, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '9', 'C', 8058, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '10', 'C', 8059, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '11', 'N', 8060, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '12', 'N', 8061, '30a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '13', 'N', 8062, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '14', 'N', 8063, '32');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '15', 'N', 8064, '33');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '16', 'N', 8065, '34');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '17', 'N', 8066, '35');

--PL 01_1_TAIN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '8', 'N', 8067, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '1', 'C', 8068, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '2', 'C', 8068, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '3', 'N', 8068, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '4', 'N', 8068, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '5', 'C', 8068, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '7', 'N', 8069, '8');

--01A_TNDN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '1', 'C', 8070, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '2', 'C', 8071, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '3', 'C', 8072, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '4', 'D', 8073, '10');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '5', 'C', 8074, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '6', 'C', 8075, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '7', 'C', 8076, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '8', 'C', 8077, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '9', 'C', 8078, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '10', 'C', 8079, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '11', 'N', 8080, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '12', 'N', 8081, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '13', 'N', 8082, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '14', 'N', 8083, '32');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '15', 'N', 8084, '33');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '16', 'N', 8085, '34');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '17', 'N', 8086, '35');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '18', 'N', 8087, '36');

--PL 01A_1_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '8', 'N', 8088, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '1', 'C', 8089, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '2', 'C', 8089, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '3', 'N', 8089, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '4', 'N', 8089, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '5', 'C', 8089, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '6', 'N', 8090, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '7', 'N', 8090, '8');

--01B_TNDN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '1', 'C', 8091, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '2', 'C', 8092, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '3', 'C', 8093, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '4', 'N', 8094, '22');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '5', 'N', 8095, '23');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '6', 'N', 8096, '24');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '7', 'N', 8097, '25');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '8', 'N', 8098, '26');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '9', 'N', 8099, '27');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '10', 'N', 8100, '28');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '11', 'N', 8101, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '12', 'N', 8102, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '13', 'N', 8103, '31');

--PL 01B_1_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '8', 'N', 8104, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '1', 'C', 8105, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '2', 'C', 8105, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '3', 'N', 8105, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '4', 'N', 8105, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '5', 'C', 8105, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '6', 'N', 8106, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '7', 'N', 8106, '8');

--03_TD_TAIN
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '1', 'C', 8107, '21');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '2', 'N', 8108, '22');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '23', 'C', 8109, '23');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '24', 'C', 8109, '24');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '25', 'N', 8109, '25');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '26', 'N', 8109, '26');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '27', 'N', 8109, '27');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '28', 'N', 8109, '28');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '29', 'N', 8109, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '30', 'N', 8110, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '31', 'N', 8110, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '32', 'N', 8110, '32');

-- PL 03_1_TD_TAIN
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '1', 'C', 8111, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '2', 'C', 8111, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '3', 'C', 8111, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '4', 'N', 8111, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '5', 'N', 8111, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '6', 'C', 8111, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '7', 'C', 8112, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '8', 'N', 8112, '8');

--01_TD_GTGT
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '21', 'N', 8113, '21');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '22', 'N', 8114, '22');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '23', 'N', 8115, '23');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '24', 'N', 8116, '24');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '25', 'N', 8117, '25');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '26', 'N', 8118, '26');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '27', 'N', 8119, '27');

--01_2_TD_GTGT
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '1', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '2', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '3', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '4', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '5', 'N', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '6', 'N', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '7', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '8', 'C', 8120, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '9', 'N', 8121, null);

