--01_TAIN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '1', 'C', 8100, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '2', 'C', 8101, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '3', 'C', 8102, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '4', 'D', 8103, '10');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '5', 'C', 8104, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '6', 'C', 8105, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '7', 'C', 8106, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '8', 'C', 8107, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '9', 'C', 8108, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '10', 'C', 8109, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '11', 'N', 8110, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '12', 'N', 8111, '30a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '13', 'N', 8112, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '14', 'N', 8113, '32');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '15', 'N', 8114, '33');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '16', 'N', 8115, '34');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TAIN_DK', '17', 'N', 8116, '35');
commit;

--PL 01_1_TAIN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '8', 'N', 8166, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '1', 'C', 8167, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '2', 'C', 8167, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '3', 'N', 8167, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '4', 'N', 8167, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '5', 'C', 8167, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1_TAIN_DK', '7', 'N', 8168, '8');
commit;

--01A_TNDN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '1', 'C', 8218, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '2', 'C', 8219, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '3', 'C', 8220, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '4', 'D', 8221, '10');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '5', 'C', 8222, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '6', 'C', 8223, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '7', 'C', 8224, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '8', 'C', 8225, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '9', 'C', 8226, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '10', 'C', 8227, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '11', 'N', 8228, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '12', 'N', 8229, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '13', 'N', 8230, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '14', 'N', 8231, '32');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '15', 'N', 8232, '33');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '16', 'N', 8233, '34');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '17', 'N', 8234, '35');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_TNDN_DK', '18', 'N', 8235, '36');
commit;

--PL 01A_1_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '8', 'N', 8285, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '1', 'C', 8286, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '2', 'C', 8286, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '3', 'N', 8286, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '4', 'N', 8286, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '5', 'C', 8286, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '6', 'N', 8287, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_1_TNDN_DK', '7', 'N', 8287, '8');
commit;

--01B_TNDN_DK	
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '1', 'C', 8337, '19');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '2', 'C', 8338, '20');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '3', 'C', 8339, '20a');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '4', 'N', 8340, '22');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '5', 'N', 8341, '23');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '6', 'N', 8342, '24');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '7', 'N', 8343, '25');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '8', 'N', 8344, '26');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '9', 'N', 8345, '27');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '10', 'N', 8346, '28');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '11', 'N', 8347, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '12', 'N', 8348, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_TNDN_DK', '13', 'N', 8349, '31');
commit;

--PL 01B_1_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '8', 'N', 8399, '9');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '1', 'C', 8400, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '2', 'C', 8400, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '3', 'N', 8400, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '4', 'N', 8400, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '5', 'C', 8400, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '6', 'N', 8401, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_1_TNDN_DK', '7', 'N', 8401, '8');
commit;

--03_TD_TAIN
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '1', 'C', 8451, '21');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '2', 'N', 8452, '22');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '23', 'C', 8453, '23');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '24', 'C', 8453, '24');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '25', 'N', 8453, '25');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '26', 'N', 8453, '26');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '27', 'N', 8453, '27');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '28', 'N', 8453, '28');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '29', 'N', 8453, '29');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '30', 'N', 8454, '30');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '31', 'N', 8454, '31');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TD_TAIN', '32', 'N', 8454, '32');
commit;

-- PL 03_1_TD_TAIN
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '1', 'C', 8504, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '2', 'C', 8504, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '3', 'C', 8504, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '4', 'N', 8504, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '5', 'N', 8504, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '6', 'C', 8504, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '7', 'C', 8504, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '8', 'C', 8504, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_1_TD_TAIN', '9', 'N', 8505, '9');
commit;

--01_TD_GTGT
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '21', 'N', 8555, '21');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '22', 'N', 8556, '22');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '23', 'N', 8557, '23');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '24', 'N', 8558, '24');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '25', 'N', 8559, '25');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '26', 'N', 8560, '26');
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) values ('01_TD_GTGT', '27', 'N', 8561, '27');
commit;

--01_2_TD_GTGT
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '1', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '2', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '3', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '4', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '5', 'N', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '6', 'N', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '7', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '8', 'C', 8611, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2_TD_GTGT', '9', 'N', 8612, null);
commit;

--01_BCTL_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '1', 'C', 8662, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '2', 'C', 8663, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '3', 'C', 8664, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '4', 'N', 8666, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '7', 'C', 8666, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '5', 'N', 8666, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '6', 'N', 8666, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '10', 'N', 8667, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '9', 'N', 8667, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '11', 'C', 8667, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '8', 'N', 8667, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '12', 'N', 8668, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '13', 'N', 8668, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '14', 'N', 8668, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '15', 'C', 8668, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '16', 'N', 8670, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '17', 'N', 8670, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '18', 'N', 8670, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '19', 'C', 8670, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '20', 'N', 8671, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '21', 'N', 8671, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '22', 'N', 8671, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '23', 'C', 8671, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '24', 'N', 8672, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '25', 'N', 8672, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '26', 'N', 8672, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '27', 'C', 8672, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '28', 'N', 8673, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '29', 'N', 8673, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '30', 'N', 8673, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '31', 'C', 8673, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '32', 'N', 8674, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '33', 'N', 8674, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '34', 'N', 8674, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '35', 'C', 8674, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '36', 'N', 8675, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '37', 'N', 8675, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '38', 'N', 8675, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_BCTL_DK', '39', 'C', 8675, null);
commit;

--KHBS_01A_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '1', 'C', 8725, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '2', 'C', 8725, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '3', 'N', 8725, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '5', 'N', 8725, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '4', 'N', 8725, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '10', 'N', 8726, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '6', 'C', 8726, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '8', 'N', 8726, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '9', 'N', 8726, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '7', 'C', 8726, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '12', 'N', 8727, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '13', 'N', 8727, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '14', 'N', 8727, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '15', 'N', 8728, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '16', 'N', 8729, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '17', 'N', 8730, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '18', 'C', 8731, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '19', 'D', 8732, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '20', 'C', 8733, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '21', 'C', 8734, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '22', 'N', 8735, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '23', 'N', 8736, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '24', 'C', 8737, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01A_TNDN_DK', '25', 'C', 8738, null);

--KHBS_01B_TNDN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '1', 'C', 8788, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '2', 'C', 8788, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '3', 'N', 8788, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '5', 'N', 8788, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '4', 'N', 8788, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '10', 'N', 8789, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '6', 'C', 8789, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '8', 'N', 8789, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '9', 'N', 8789, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '7', 'C', 8789, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '12', 'N', 8790, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '13', 'N', 8790, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '14', 'N', 8790, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '15', 'N', 8791, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '16', 'N', 8792, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '17', 'N', 8793, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '18', 'C', 8794, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '19', 'D', 8795, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '20', 'C', 8796, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '21', 'C', 8797, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '22', 'N', 8798, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '23', 'N', 8799, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '24', 'C', 8800, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01B_TNDN_DK', '25', 'C', 8801, null);
commit;

--KHBS_01_TD_GTGT
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '1', 'C', 8851, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '2', 'C', 8851, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '3', 'N', 8851, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '5', 'N', 8851, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '4', 'N', 8851, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '10', 'N', 8852, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '6', 'C', 8852, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '8', 'N', 8852, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '9', 'N', 8852, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '7', 'C', 8852, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '12', 'N', 8853, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '13', 'N', 8853, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '14', 'N', 8853, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '15', 'N', 8854, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '16', 'N', 8855, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '17', 'N', 8856, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '18', 'C', 8857, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '19', 'D', 8858, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '20', 'C', 8859, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '21', 'C', 8860, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '22', 'N', 8861, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '23', 'N', 8862, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '24', 'C', 8863, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TD_GTGT', '25', 'C', 8864, null);
commit;

--KHBS_03_TD_TAIN
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '1', 'C', 8914, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '2', 'C', 8914, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '3', 'N', 8914, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '5', 'N', 8914, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '4', 'N', 8914, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '10', 'N', 8915, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '6', 'C', 8915, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '8', 'N', 8915, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '9', 'N', 8915, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '7', 'C', 8915, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '12', 'N', 8916, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '13', 'N', 8916, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '14', 'N', 8916, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '15', 'N', 8917, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '16', 'N', 8918, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '17', 'N', 8919, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '18', 'C', 8920, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '19', 'D', 8921, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '20', 'C', 8922, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '21', 'C', 8923, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '22', 'N', 8924, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '23', 'N', 8925, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '24', 'C', 8926, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_03_TD_TAIN', '25', 'C', 8927, null);
commit;

--KHBS_01_TAIN_DK
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '1', 'C', 8977, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '2', 'C', 8977, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '3', 'N', 8977, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '5', 'N', 8977, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '4', 'N', 8977, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '10', 'N', 8978, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '6', 'C', 8978, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '8', 'N', 8978, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '9', 'N', 8978, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '7', 'C', 8978, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '12', 'N', 8979, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '13', 'N', 8979, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '14', 'N', 8979, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '15', 'N', 8980, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '16', 'N', 8981, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '17', 'N', 8982, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '18', 'C', 8983, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '19', 'D', 8984, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '20', 'C', 8985, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '21', 'C', 8986, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '22', 'N', 8987, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '23', 'N', 8988, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '24', 'C', 8989, null);
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('KHBS_01_TAIN_DK', '25', 'C', 8990, null);
commit;

--01/GTGT PL 01_1TD_GTGT13
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1TD_GTGT13', '2', 'C', 9040, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1TD_GTGT13', '3', 'N', 9040, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1TD_GTGT13', '4', 'N', 9040, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1TD_GTGT13', '5', 'N', 9040, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_1TD_GTGT13', '6', 'N', 9040, '6');
commit;

--01/GTGT PL 01_2TD_GTGT13
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '1', 'C', 9090, '1');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '2', 'C', 9090, '2');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '3', 'C', 9090, '3');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '4', 'N', 9090, '4');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '5', 'N', 9090, '5');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '6', 'C', 9090, '6');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '7', 'C', 9090, '7');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '8', 'C', 9090, '8');
INSERT INTO QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_2TD_GTGT13', '9', 'N', 9091, '9');
commit;

--01A/TNDN PL 02/TD-TNDN
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '1', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '2', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '3', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '4', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '5', 'N', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '6', 'N', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '7', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '8', 'C', 9041, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01A_2_TD_TNDN13', '9', 'N', 9042, null);
commit;

--01B/TNDN PL 02/TD-TNDN
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '1', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '2', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '3', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '4', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '5', 'N', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '6', 'N', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '7', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '8', 'C', 9092, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01B_2_TD_TNDN13', '9', 'N', 9093, null);
commit;
