--BC21_AC_BLP
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '1', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '2', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '3', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '4', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '5', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '6', 'N', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '7', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '8', 'C', 7948, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('BC21_AC_BLP', '9', 'N', 7948, null);
--03_TBAC_BLP
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '1', 'C', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '2', 'C', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '3', 'C', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '4', 'N', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '5', 'N', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '6', 'N', 7947, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('03_TBAC_BLP', '7', 'N', 7947, null);
--01_TBAC_BLP
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '1', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '2', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '3', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '4', 'N', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '5', 'N', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '6', 'N', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '7', 'D', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '8', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '9', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '10', 'C', 7946, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_TBAC_BLP', '11', 'C', 7946, null);
--01_AC_BLP
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '1', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '2', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '3', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '4', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '5', 'D', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '6', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '7', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '8', 'C', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '9', 'N', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '10', 'N', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '11', 'N', 7949, null);
INSERT INTO RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU) VALUES ('01_AC_BLP', '12', 'N', 7949, null);
