--09A_TNDN11

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '5', 'N', 10000, '5');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '6', 'N', 10001, '6');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '7', 'N', 10002, '7');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '8', 'N', 10003, '8');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '9', 'N', 10004, '9');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '10', 'N', 10005, '10');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '11', 'N', 10006, '11');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '12', 'N', 10007, '12');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09A_TNCN11', '13', 'N', 10008, '13');

commit;

--09B_TNDN11

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '5', 'N', 10028, '5');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '6', 'N', 10029, '6');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '7', 'N', 10030, '7');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '8', 'N', 10031, '8');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '9', 'N', 10032, '9');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '10', 'N', 10033, '10');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '11', 'N', 10034, '11');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '12', 'N', 10035, '12');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '13', 'N', 10036, '13');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '14', 'N', 10037, '14');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '15', 'N', 10038, '15');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '16', 'N', 10039, '16');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '17', 'N', 10040, '17');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '18', 'N', 10041, '18');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '19', 'N', 10042, '19');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09B_TNCN11', '20', 'N', 10043, '20');

commit;

--09C_TNDN11

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '3', 'C', 10063, '3');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '4', 'C', 10064, '4');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '5', 'C', 10065, '5');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '9', 'C', 10066, '9');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '10', 'D', 10066, '10');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '11', 'C', 10066, '11');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '12', 'C', 10066, '12');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '13', 'C', 10066, '13');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '14', 'N', 10066, '14');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09C_TNCN11', '15', 'N', 10066, '15');

commit;

--09MT_TNDN11

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09MT_TNCN11', '6', 'N', 10086, '6');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09MT_TNCN11', '7', 'N', 10087, '7');

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('09MT_TNCN11', '8', 'N', 10088, '8');

commit;

--BC26_AC_SL
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '1', 'C', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '2', 'C', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '3', 'C', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '4', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '5', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '6', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '7', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '8', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '9', 'C', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '10', 'C', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '11', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '12', 'N', 10138, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BC26_AC_SL', '13', 'C', 10138, null);

commit;

--PL BK26SL_01_AC
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '1', 'C', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '2', 'C', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '3', 'C', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '4', 'N', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '5', 'N', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '6', 'N', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '7', 'N', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '8', 'N', 10139, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '9', 'C', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '10', 'C', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '11', 'C', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '12', 'N', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '13', 'N', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '14', 'N', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '15', 'N', 10140, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_01_AC', '16', 'N', 10140, null);

commit;

--PL BK26SL_02_AC
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '1', 'C', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '2', 'C', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '3', 'C', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '4', 'N', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '5', 'N', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '6', 'N', 10141, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('BK26SL_02_AC', '7', 'N', 10141, null);

commit;

--To Khai 01_BK_BC26_AC
insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '1', 'C', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '2', 'C', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '3', 'C', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '4', 'N', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '5', 'C', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '6', 'C', 10191, null);

insert into QLT_NTK.RCV_MAP_CTIEU (LOAI_DLIEU, KY_HIEU, KIEU_DLIEU, GDN_ID, KY_HIEU_CTIEU)
values ('01_BK_BC26_AC', '7', 'C', 10191, null);

commit;
