--Connect User QLT_RECV
CREATE PUBLIC SYNONYM RCV_MAP_TKHAI FOR RCV_MAP_TKHAI
/
GRANT SELECT ON RCV_MAP_TKHAI TO QLT
/
GRANT SELECT ON RCV_MAP_TKHAI TO QLT_OWNER
/
CREATE PUBLIC SYNONYM RCV_TKHAI_HDR FOR RCV_TKHAI_HDR
/
GRANT SELECT ON RCV_TKHAI_HDR TO QLT
/
GRANT SELECT ON RCV_TKHAI_HDR TO QLT_OWNER
/
