--connect sys/change_on_install@qlt

CREATE TABLESPACE "QLT_RECV_DATA" 
    LOGGING 
    DATAFILE 'E:\DATABASE\QLT\QLT_RECV_DATA_01.ORA' SIZE 512M 
    AUTOEXTEND 
    ON NEXT  10240K MAXSIZE  1024M EXTENT MANAGEMENT LOCAL
/
CREATE USER qlt_recv
IDENTIFIED BY qlt_recv
DEFAULT TABLESPACE QLT_RECV_DATA
TEMPORARY TABLESPACE QLT_TEMP
QUOTA UNLIMITED ON QLT_RECV_DATA
QUOTA UNLIMITED ON QLT_TEMP
/
GRANT CONNECT, RESOURCE TO qlt_recv
/
GRANT CREATE ANY SEQUENCE TO qlt_recv
/
GRANT CREATE PUBLIC DATABASE LINK TO qlt_recv
/
GRANT CREATE PUBLIC SYNONYM TO qlt_recv
/
GRANT DROP ANY SEQUENCE TO qlt_recv
/
GRANT DROP PUBLIC DATABASE LINK TO qlt_recv
/
GRANT DROP PUBLIC SYNONYM TO qlt_recv
/
GRANT UNLIMITED TABLESPACE TO qlt_recv
/

